device_type: RS16             #@type: string @brief: the device type  ***RS32 or RS16***
frame_id: /left_lidar         #@type: string @brief: the frame id of the message
device_ip: 192.168.1.199      #@type: string @brief: the lidar ip address
msop_port: 1990               #@type: uint16_t @brief: the MSOP packets port
difop_port: 1991              #@type: uint16_t @brief: the DIFOP packets port
resolution_type: 0            #@type: int @brief: user need to set this correspond to the specific LiDAR
                              #                   0--0.5cm, 1--1cm
intensity_mode: 3             #@type: int @brief: user need to set this correspond to the specific LiDAR
start_angle: 0                #@type: int @brief: the start angle of point cloud area
end_angle: 360                #@type: int @brief: the end angle of point cloud area
min_distance: 0.4             #@type: int @brief: the minimum distance of point cloud area
max_distance: 150             #@type: int @brief: the maximum distance of point cloud area
cut_angle: 0                 #@type: int @area 0~360
                              #@brief: the angle to separate LiDAR scan frame
pcap: /home/robosense/p3_left.pcap    #@type: string @brief the path of pcap bag
read_pcap: false              #@type: bool @brief: if ture, the lidar driver will read message from pcap bag
use_lidar_clock: false        #@type: bool @brief: if false--use system clock,if true--use lidar clock
timeout: 100                  #@type: bool @unit: ms
                              #@brief: time to detect lidar disconnection
