// Generated by gencpp from file rs_perception/freespace_set_ros_msg.msg
// DO NOT EDIT!


#ifndef RS_PERCEPTION_MESSAGE_FREESPACE_SET_ROS_MSG_H
#define RS_PERCEPTION_MESSAGE_FREESPACE_SET_ROS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <panta_common/msg/ros_msg/freespace_ros_msg.h>

namespace rs_perception
{
template <class ContainerAllocator>
struct freespace_set_ros_msg_
{
  typedef freespace_set_ros_msg_<ContainerAllocator> Type;

  freespace_set_ros_msg_()
    : header()
    , freespaces()  {
    }
  freespace_set_ros_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , freespaces(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rs_perception::freespace_ros_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rs_perception::freespace_ros_msg_<ContainerAllocator> >::other >  _freespaces_type;
  _freespaces_type freespaces;





  typedef boost::shared_ptr< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> const> ConstPtr;

}; // struct freespace_set_ros_msg_

typedef ::rs_perception::freespace_set_ros_msg_<std::allocator<void> > freespace_set_ros_msg;

typedef boost::shared_ptr< ::rs_perception::freespace_set_ros_msg > freespace_set_ros_msgPtr;
typedef boost::shared_ptr< ::rs_perception::freespace_set_ros_msg const> freespace_set_ros_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rs_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rs_perception': ['/home/wangbin/DEVELOP/rs_ws/src/rs_perception/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81d6d97df6b7f688fef0390d0121841b";
  }

  static const char* value(const ::rs_perception::freespace_set_ros_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81d6d97df6b7f688ULL;
  static const uint64_t static_value2 = 0xfef0390d0121841bULL;
};

template<class ContainerAllocator>
struct DataType< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rs_perception/freespace_set_ros_msg";
  }

  static const char* value(const ::rs_perception::freespace_set_ros_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# perception list, defined by ros message type\n\
\n\
Header                    header                   # standard ROS message header\n\
\n\
freespace_ros_msg[] freespaces # free drivable zone, organized in polar system with distance to the nearest obstacle that block the way\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: rs_perception/freespace_ros_msg\n\
# freespace ros message, organized in polar system with distance to the nearest obstacle that block the way\n\
\n\
# ============basic info============\n\
float64 timestamp # global timestamp in seconds.\n\
uint32 device_code # which device the obstacle is detected by.\n\
\n\
float32 distance\n\
float32 yaw_angle\n\
float32 free_prob\n\
";
  }

  static const char* value(const ::rs_perception::freespace_set_ros_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.freespaces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct freespace_set_ros_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rs_perception::freespace_set_ros_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rs_perception::freespace_set_ros_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "freespaces[]" << std::endl;
    for (size_t i = 0; i < v.freespaces.size(); ++i)
    {
      s << indent << "  freespaces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rs_perception::freespace_ros_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.freespaces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RS_PERCEPTION_MESSAGE_FREESPACE_SET_ROS_MSG_H
