// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.GridMap.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Proto_msg.GridMap.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Proto_msg {
class GridMapDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GridMap>
     _instance;
} _GridMap_default_instance_;

namespace protobuf_Proto_5fmsg_2eGridMap_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, seq_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, parent_frame_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, frame_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, resolution_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, origin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, orientation_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GridMap, grids_),
  2,
  3,
  0,
  1,
  4,
  5,
  6,
  ~0u,
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 15, sizeof(GridMap)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_GridMap_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Proto_msg.GridMap.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _GridMap_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_GridMap_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027Proto_msg.GridMap.proto\022\tProto_msg\"\273\001\n"
      "\007GridMap\022\021\n\ttimestamp\030\001 \001(\001\022\013\n\003seq\030\002 \001(\r"
      "\022\027\n\017parent_frame_id\030\003 \001(\t\022\020\n\010frame_id\030\004 "
      "\001(\t\022\r\n\005width\030\005 \001(\r\022\016\n\006height\030\006 \001(\r\022\022\n\nre"
      "solution\030\007 \001(\002\022\016\n\006origin\030\010 \003(\002\022\023\n\013orient"
      "ation\030\t \003(\002\022\r\n\005grids\030\n \003(\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 226);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto_msg.GridMap.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Proto_5fmsg_2eGridMap_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GridMap::kTimestampFieldNumber;
const int GridMap::kSeqFieldNumber;
const int GridMap::kParentFrameIdFieldNumber;
const int GridMap::kFrameIdFieldNumber;
const int GridMap::kWidthFieldNumber;
const int GridMap::kHeightFieldNumber;
const int GridMap::kResolutionFieldNumber;
const int GridMap::kOriginFieldNumber;
const int GridMap::kOrientationFieldNumber;
const int GridMap::kGridsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GridMap::GridMap()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Proto_5fmsg_2eGridMap_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Proto_msg.GridMap)
}
GridMap::GridMap(const GridMap& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      origin_(from.origin_),
      orientation_(from.orientation_),
      grids_(from.grids_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  parent_frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_parent_frame_id()) {
    parent_frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parent_frame_id_);
  }
  frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_frame_id()) {
    frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_id_);
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&resolution_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(resolution_));
  // @@protoc_insertion_point(copy_constructor:Proto_msg.GridMap)
}

void GridMap::SharedCtor() {
  _cached_size_ = 0;
  parent_frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resolution_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(resolution_));
}

GridMap::~GridMap() {
  // @@protoc_insertion_point(destructor:Proto_msg.GridMap)
  SharedDtor();
}

void GridMap::SharedDtor() {
  parent_frame_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GridMap::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GridMap::descriptor() {
  protobuf_Proto_5fmsg_2eGridMap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Proto_5fmsg_2eGridMap_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GridMap& GridMap::default_instance() {
  protobuf_Proto_5fmsg_2eGridMap_2eproto::InitDefaults();
  return *internal_default_instance();
}

GridMap* GridMap::New(::google::protobuf::Arena* arena) const {
  GridMap* n = new GridMap;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GridMap::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto_msg.GridMap)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  origin_.Clear();
  orientation_.Clear();
  grids_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!parent_frame_id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*parent_frame_id_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!frame_id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*frame_id_.UnsafeRawStringPointer())->clear();
    }
  }
  if (cached_has_bits & 124u) {
    ::memset(&timestamp_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&resolution_) -
        reinterpret_cast<char*>(&timestamp_)) + sizeof(resolution_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool GridMap::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Proto_msg.GridMap)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_timestamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 seq = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_seq();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seq_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string parent_frame_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parent_frame_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parent_frame_id().data(), static_cast<int>(this->parent_frame_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Proto_msg.GridMap.parent_frame_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string frame_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_frame_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->frame_id().data(), static_cast<int>(this->frame_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Proto_msg.GridMap.frame_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 width = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 height = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_height();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float resolution = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {
          set_has_resolution();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &resolution_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float origin = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(69u /* 69 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 69u, input, this->mutable_origin())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_origin())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float orientation = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(77u /* 77 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 77u, input, this->mutable_orientation())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_orientation())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float grids = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(85u /* 85 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 85u, input, this->mutable_grids())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_grids())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Proto_msg.GridMap)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Proto_msg.GridMap)
  return false;
#undef DO_
}

void GridMap::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Proto_msg.GridMap)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double timestamp = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->timestamp(), output);
  }

  // optional uint32 seq = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->seq(), output);
  }

  // optional string parent_frame_id = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_frame_id().data(), static_cast<int>(this->parent_frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Proto_msg.GridMap.parent_frame_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->parent_frame_id(), output);
  }

  // optional string frame_id = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), static_cast<int>(this->frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Proto_msg.GridMap.frame_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->frame_id(), output);
  }

  // optional uint32 width = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->width(), output);
  }

  // optional uint32 height = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->height(), output);
  }

  // optional float resolution = 7;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->resolution(), output);
  }

  // repeated float origin = 8;
  for (int i = 0, n = this->origin_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      8, this->origin(i), output);
  }

  // repeated float orientation = 9;
  for (int i = 0, n = this->orientation_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      9, this->orientation(i), output);
  }

  // repeated float grids = 10;
  for (int i = 0, n = this->grids_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      10, this->grids(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Proto_msg.GridMap)
}

::google::protobuf::uint8* GridMap::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Proto_msg.GridMap)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double timestamp = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->timestamp(), target);
  }

  // optional uint32 seq = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->seq(), target);
  }

  // optional string parent_frame_id = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_frame_id().data(), static_cast<int>(this->parent_frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Proto_msg.GridMap.parent_frame_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->parent_frame_id(), target);
  }

  // optional string frame_id = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), static_cast<int>(this->frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Proto_msg.GridMap.frame_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->frame_id(), target);
  }

  // optional uint32 width = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->width(), target);
  }

  // optional uint32 height = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->height(), target);
  }

  // optional float resolution = 7;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->resolution(), target);
  }

  // repeated float origin = 8;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(8, this->origin_, target);

  // repeated float orientation = 9;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(9, this->orientation_, target);

  // repeated float grids = 10;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(10, this->grids_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto_msg.GridMap)
  return target;
}

size_t GridMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto_msg.GridMap)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated float origin = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->origin_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->origin_size());
    total_size += data_size;
  }

  // repeated float orientation = 9;
  {
    unsigned int count = static_cast<unsigned int>(this->orientation_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->orientation_size());
    total_size += data_size;
  }

  // repeated float grids = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->grids_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->grids_size());
    total_size += data_size;
  }

  if (_has_bits_[0 / 32] & 127u) {
    // optional string parent_frame_id = 3;
    if (has_parent_frame_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->parent_frame_id());
    }

    // optional string frame_id = 4;
    if (has_frame_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->frame_id());
    }

    // optional double timestamp = 1;
    if (has_timestamp()) {
      total_size += 1 + 8;
    }

    // optional uint32 seq = 2;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->seq());
    }

    // optional uint32 width = 5;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->width());
    }

    // optional uint32 height = 6;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->height());
    }

    // optional float resolution = 7;
    if (has_resolution()) {
      total_size += 1 + 4;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GridMap::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto_msg.GridMap)
  GOOGLE_DCHECK_NE(&from, this);
  const GridMap* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GridMap>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto_msg.GridMap)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto_msg.GridMap)
    MergeFrom(*source);
  }
}

void GridMap::MergeFrom(const GridMap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto_msg.GridMap)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  origin_.MergeFrom(from.origin_);
  orientation_.MergeFrom(from.orientation_);
  grids_.MergeFrom(from.grids_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_parent_frame_id();
      parent_frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parent_frame_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_frame_id();
      frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_id_);
    }
    if (cached_has_bits & 0x00000004u) {
      timestamp_ = from.timestamp_;
    }
    if (cached_has_bits & 0x00000008u) {
      seq_ = from.seq_;
    }
    if (cached_has_bits & 0x00000010u) {
      width_ = from.width_;
    }
    if (cached_has_bits & 0x00000020u) {
      height_ = from.height_;
    }
    if (cached_has_bits & 0x00000040u) {
      resolution_ = from.resolution_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void GridMap::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto_msg.GridMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GridMap::CopyFrom(const GridMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto_msg.GridMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GridMap::IsInitialized() const {
  return true;
}

void GridMap::Swap(GridMap* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GridMap::InternalSwap(GridMap* other) {
  using std::swap;
  origin_.InternalSwap(&other->origin_);
  orientation_.InternalSwap(&other->orientation_);
  grids_.InternalSwap(&other->grids_);
  parent_frame_id_.Swap(&other->parent_frame_id_);
  frame_id_.Swap(&other->frame_id_);
  swap(timestamp_, other->timestamp_);
  swap(seq_, other->seq_);
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(resolution_, other->resolution_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GridMap::GetMetadata() const {
  protobuf_Proto_5fmsg_2eGridMap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Proto_5fmsg_2eGridMap_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GridMap

// optional double timestamp = 1;
bool GridMap::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void GridMap::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
void GridMap::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
void GridMap::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
double GridMap::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.timestamp)
  return timestamp_;
}
void GridMap::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.timestamp)
}

// optional uint32 seq = 2;
bool GridMap::has_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void GridMap::set_has_seq() {
  _has_bits_[0] |= 0x00000008u;
}
void GridMap::clear_has_seq() {
  _has_bits_[0] &= ~0x00000008u;
}
void GridMap::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
::google::protobuf::uint32 GridMap::seq() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.seq)
  return seq_;
}
void GridMap::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.seq)
}

// optional string parent_frame_id = 3;
bool GridMap::has_parent_frame_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GridMap::set_has_parent_frame_id() {
  _has_bits_[0] |= 0x00000001u;
}
void GridMap::clear_has_parent_frame_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void GridMap::clear_parent_frame_id() {
  parent_frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parent_frame_id();
}
const ::std::string& GridMap::parent_frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.parent_frame_id)
  return parent_frame_id_.GetNoArena();
}
void GridMap::set_parent_frame_id(const ::std::string& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.parent_frame_id)
}
#if LANG_CXX11
void GridMap::set_parent_frame_id(::std::string&& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.GridMap.parent_frame_id)
}
#endif
void GridMap::set_parent_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.GridMap.parent_frame_id)
}
void GridMap::set_parent_frame_id(const char* value, size_t size) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.GridMap.parent_frame_id)
}
::std::string* GridMap::mutable_parent_frame_id() {
  set_has_parent_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.GridMap.parent_frame_id)
  return parent_frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* GridMap::release_parent_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.GridMap.parent_frame_id)
  clear_has_parent_frame_id();
  return parent_frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void GridMap::set_allocated_parent_frame_id(::std::string* parent_frame_id) {
  if (parent_frame_id != NULL) {
    set_has_parent_frame_id();
  } else {
    clear_has_parent_frame_id();
  }
  parent_frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent_frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.GridMap.parent_frame_id)
}

// optional string frame_id = 4;
bool GridMap::has_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void GridMap::set_has_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
void GridMap::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void GridMap::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_frame_id();
}
const ::std::string& GridMap::frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.frame_id)
  return frame_id_.GetNoArena();
}
void GridMap::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.frame_id)
}
#if LANG_CXX11
void GridMap::set_frame_id(::std::string&& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.GridMap.frame_id)
}
#endif
void GridMap::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.GridMap.frame_id)
}
void GridMap::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.GridMap.frame_id)
}
::std::string* GridMap::mutable_frame_id() {
  set_has_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.GridMap.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* GridMap::release_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.GridMap.frame_id)
  clear_has_frame_id();
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void GridMap::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    set_has_frame_id();
  } else {
    clear_has_frame_id();
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.GridMap.frame_id)
}

// optional uint32 width = 5;
bool GridMap::has_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void GridMap::set_has_width() {
  _has_bits_[0] |= 0x00000010u;
}
void GridMap::clear_has_width() {
  _has_bits_[0] &= ~0x00000010u;
}
void GridMap::clear_width() {
  width_ = 0u;
  clear_has_width();
}
::google::protobuf::uint32 GridMap::width() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.width)
  return width_;
}
void GridMap::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.width)
}

// optional uint32 height = 6;
bool GridMap::has_height() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void GridMap::set_has_height() {
  _has_bits_[0] |= 0x00000020u;
}
void GridMap::clear_has_height() {
  _has_bits_[0] &= ~0x00000020u;
}
void GridMap::clear_height() {
  height_ = 0u;
  clear_has_height();
}
::google::protobuf::uint32 GridMap::height() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.height)
  return height_;
}
void GridMap::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.height)
}

// optional float resolution = 7;
bool GridMap::has_resolution() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void GridMap::set_has_resolution() {
  _has_bits_[0] |= 0x00000040u;
}
void GridMap::clear_has_resolution() {
  _has_bits_[0] &= ~0x00000040u;
}
void GridMap::clear_resolution() {
  resolution_ = 0;
  clear_has_resolution();
}
float GridMap::resolution() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.resolution)
  return resolution_;
}
void GridMap::set_resolution(float value) {
  set_has_resolution();
  resolution_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.resolution)
}

// repeated float origin = 8;
int GridMap::origin_size() const {
  return origin_.size();
}
void GridMap::clear_origin() {
  origin_.Clear();
}
float GridMap::origin(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.origin)
  return origin_.Get(index);
}
void GridMap::set_origin(int index, float value) {
  origin_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.origin)
}
void GridMap::add_origin(float value) {
  origin_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.origin)
}
const ::google::protobuf::RepeatedField< float >&
GridMap::origin() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.origin)
  return origin_;
}
::google::protobuf::RepeatedField< float >*
GridMap::mutable_origin() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.origin)
  return &origin_;
}

// repeated float orientation = 9;
int GridMap::orientation_size() const {
  return orientation_.size();
}
void GridMap::clear_orientation() {
  orientation_.Clear();
}
float GridMap::orientation(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.orientation)
  return orientation_.Get(index);
}
void GridMap::set_orientation(int index, float value) {
  orientation_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.orientation)
}
void GridMap::add_orientation(float value) {
  orientation_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.orientation)
}
const ::google::protobuf::RepeatedField< float >&
GridMap::orientation() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.orientation)
  return orientation_;
}
::google::protobuf::RepeatedField< float >*
GridMap::mutable_orientation() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.orientation)
  return &orientation_;
}

// repeated float grids = 10;
int GridMap::grids_size() const {
  return grids_.size();
}
void GridMap::clear_grids() {
  grids_.Clear();
}
float GridMap::grids(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.grids)
  return grids_.Get(index);
}
void GridMap::set_grids(int index, float value) {
  grids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.grids)
}
void GridMap::add_grids(float value) {
  grids_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.grids)
}
const ::google::protobuf::RepeatedField< float >&
GridMap::grids() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.grids)
  return grids_;
}
::google::protobuf::RepeatedField< float >*
GridMap::mutable_grids() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.grids)
  return &grids_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto_msg

// @@protoc_insertion_point(global_scope)
