// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.GridMap.proto

#ifndef PROTOBUF_Proto_5fmsg_2eGridMap_2eproto__INCLUDED
#define PROTOBUF_Proto_5fmsg_2eGridMap_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Proto_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Proto_5fmsg_2eGridMap_2eproto();
void protobuf_AssignDesc_Proto_5fmsg_2eGridMap_2eproto();
void protobuf_ShutdownFile_Proto_5fmsg_2eGridMap_2eproto();

class GridMap;

// ===================================================================

class GridMap : public ::google::protobuf::Message {
 public:
  GridMap();
  virtual ~GridMap();

  GridMap(const GridMap& from);

  inline GridMap& operator=(const GridMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GridMap& default_instance();

  void Swap(GridMap* other);

  // implements Message ----------------------------------------------

  GridMap* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GridMap& from);
  void MergeFrom(const GridMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline double timestamp() const;
  inline void set_timestamp(double value);

  // optional uint32 seq = 2;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 2;
  inline ::google::protobuf::uint32 seq() const;
  inline void set_seq(::google::protobuf::uint32 value);

  // optional string parent_frame_id = 3;
  inline bool has_parent_frame_id() const;
  inline void clear_parent_frame_id();
  static const int kParentFrameIdFieldNumber = 3;
  inline const ::std::string& parent_frame_id() const;
  inline void set_parent_frame_id(const ::std::string& value);
  inline void set_parent_frame_id(const char* value);
  inline void set_parent_frame_id(const char* value, size_t size);
  inline ::std::string* mutable_parent_frame_id();
  inline ::std::string* release_parent_frame_id();
  inline void set_allocated_parent_frame_id(::std::string* parent_frame_id);

  // optional string frame_id = 4;
  inline bool has_frame_id() const;
  inline void clear_frame_id();
  static const int kFrameIdFieldNumber = 4;
  inline const ::std::string& frame_id() const;
  inline void set_frame_id(const ::std::string& value);
  inline void set_frame_id(const char* value);
  inline void set_frame_id(const char* value, size_t size);
  inline ::std::string* mutable_frame_id();
  inline ::std::string* release_frame_id();
  inline void set_allocated_frame_id(::std::string* frame_id);

  // optional uint32 width = 5;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 5;
  inline ::google::protobuf::uint32 width() const;
  inline void set_width(::google::protobuf::uint32 value);

  // optional uint32 height = 6;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 6;
  inline ::google::protobuf::uint32 height() const;
  inline void set_height(::google::protobuf::uint32 value);

  // optional float resolution = 7;
  inline bool has_resolution() const;
  inline void clear_resolution();
  static const int kResolutionFieldNumber = 7;
  inline float resolution() const;
  inline void set_resolution(float value);

  // repeated float origin = 8;
  inline int origin_size() const;
  inline void clear_origin();
  static const int kOriginFieldNumber = 8;
  inline float origin(int index) const;
  inline void set_origin(int index, float value);
  inline void add_origin(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      origin() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_origin();

  // repeated float orientation = 9;
  inline int orientation_size() const;
  inline void clear_orientation();
  static const int kOrientationFieldNumber = 9;
  inline float orientation(int index) const;
  inline void set_orientation(int index, float value);
  inline void add_orientation(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      orientation() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_orientation();

  // repeated float grids = 10;
  inline int grids_size() const;
  inline void clear_grids();
  static const int kGridsFieldNumber = 10;
  inline float grids(int index) const;
  inline void set_grids(int index, float value);
  inline void add_grids(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      grids() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_grids();

  // @@protoc_insertion_point(class_scope:Proto_msg.GridMap)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_seq();
  inline void clear_has_seq();
  inline void set_has_parent_frame_id();
  inline void clear_has_parent_frame_id();
  inline void set_has_frame_id();
  inline void clear_has_frame_id();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_resolution();
  inline void clear_has_resolution();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double timestamp_;
  ::std::string* parent_frame_id_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 width_;
  ::std::string* frame_id_;
  ::google::protobuf::uint32 height_;
  float resolution_;
  ::google::protobuf::RepeatedField< float > origin_;
  ::google::protobuf::RepeatedField< float > orientation_;
  ::google::protobuf::RepeatedField< float > grids_;
  friend void  protobuf_AddDesc_Proto_5fmsg_2eGridMap_2eproto();
  friend void protobuf_AssignDesc_Proto_5fmsg_2eGridMap_2eproto();
  friend void protobuf_ShutdownFile_Proto_5fmsg_2eGridMap_2eproto();

  void InitAsDefaultInstance();
  static GridMap* default_instance_;
};
// ===================================================================


// ===================================================================

// GridMap

// optional double timestamp = 1;
inline bool GridMap::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GridMap::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GridMap::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GridMap::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double GridMap::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.timestamp)
  return timestamp_;
}
inline void GridMap::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.timestamp)
}

// optional uint32 seq = 2;
inline bool GridMap::has_seq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GridMap::set_has_seq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GridMap::clear_has_seq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GridMap::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 GridMap::seq() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.seq)
  return seq_;
}
inline void GridMap::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.seq)
}

// optional string parent_frame_id = 3;
inline bool GridMap::has_parent_frame_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GridMap::set_has_parent_frame_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GridMap::clear_has_parent_frame_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GridMap::clear_parent_frame_id() {
  if (parent_frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    parent_frame_id_->clear();
  }
  clear_has_parent_frame_id();
}
inline const ::std::string& GridMap::parent_frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.parent_frame_id)
  return *parent_frame_id_;
}
inline void GridMap::set_parent_frame_id(const ::std::string& value) {
  set_has_parent_frame_id();
  if (parent_frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    parent_frame_id_ = new ::std::string;
  }
  parent_frame_id_->assign(value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.parent_frame_id)
}
inline void GridMap::set_parent_frame_id(const char* value) {
  set_has_parent_frame_id();
  if (parent_frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    parent_frame_id_ = new ::std::string;
  }
  parent_frame_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:Proto_msg.GridMap.parent_frame_id)
}
inline void GridMap::set_parent_frame_id(const char* value, size_t size) {
  set_has_parent_frame_id();
  if (parent_frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    parent_frame_id_ = new ::std::string;
  }
  parent_frame_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.GridMap.parent_frame_id)
}
inline ::std::string* GridMap::mutable_parent_frame_id() {
  set_has_parent_frame_id();
  if (parent_frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    parent_frame_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Proto_msg.GridMap.parent_frame_id)
  return parent_frame_id_;
}
inline ::std::string* GridMap::release_parent_frame_id() {
  clear_has_parent_frame_id();
  if (parent_frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = parent_frame_id_;
    parent_frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GridMap::set_allocated_parent_frame_id(::std::string* parent_frame_id) {
  if (parent_frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete parent_frame_id_;
  }
  if (parent_frame_id) {
    set_has_parent_frame_id();
    parent_frame_id_ = parent_frame_id;
  } else {
    clear_has_parent_frame_id();
    parent_frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.GridMap.parent_frame_id)
}

// optional string frame_id = 4;
inline bool GridMap::has_frame_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GridMap::set_has_frame_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GridMap::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GridMap::clear_frame_id() {
  if (frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    frame_id_->clear();
  }
  clear_has_frame_id();
}
inline const ::std::string& GridMap::frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.frame_id)
  return *frame_id_;
}
inline void GridMap::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  if (frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    frame_id_ = new ::std::string;
  }
  frame_id_->assign(value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.frame_id)
}
inline void GridMap::set_frame_id(const char* value) {
  set_has_frame_id();
  if (frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    frame_id_ = new ::std::string;
  }
  frame_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:Proto_msg.GridMap.frame_id)
}
inline void GridMap::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  if (frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    frame_id_ = new ::std::string;
  }
  frame_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.GridMap.frame_id)
}
inline ::std::string* GridMap::mutable_frame_id() {
  set_has_frame_id();
  if (frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    frame_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Proto_msg.GridMap.frame_id)
  return frame_id_;
}
inline ::std::string* GridMap::release_frame_id() {
  clear_has_frame_id();
  if (frame_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = frame_id_;
    frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GridMap::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete frame_id_;
  }
  if (frame_id) {
    set_has_frame_id();
    frame_id_ = frame_id;
  } else {
    clear_has_frame_id();
    frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.GridMap.frame_id)
}

// optional uint32 width = 5;
inline bool GridMap::has_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GridMap::set_has_width() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GridMap::clear_has_width() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GridMap::clear_width() {
  width_ = 0u;
  clear_has_width();
}
inline ::google::protobuf::uint32 GridMap::width() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.width)
  return width_;
}
inline void GridMap::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.width)
}

// optional uint32 height = 6;
inline bool GridMap::has_height() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GridMap::set_has_height() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GridMap::clear_has_height() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GridMap::clear_height() {
  height_ = 0u;
  clear_has_height();
}
inline ::google::protobuf::uint32 GridMap::height() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.height)
  return height_;
}
inline void GridMap::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.height)
}

// optional float resolution = 7;
inline bool GridMap::has_resolution() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GridMap::set_has_resolution() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GridMap::clear_has_resolution() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GridMap::clear_resolution() {
  resolution_ = 0;
  clear_has_resolution();
}
inline float GridMap::resolution() const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.resolution)
  return resolution_;
}
inline void GridMap::set_resolution(float value) {
  set_has_resolution();
  resolution_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.resolution)
}

// repeated float origin = 8;
inline int GridMap::origin_size() const {
  return origin_.size();
}
inline void GridMap::clear_origin() {
  origin_.Clear();
}
inline float GridMap::origin(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.origin)
  return origin_.Get(index);
}
inline void GridMap::set_origin(int index, float value) {
  origin_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.origin)
}
inline void GridMap::add_origin(float value) {
  origin_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.origin)
}
inline const ::google::protobuf::RepeatedField< float >&
GridMap::origin() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.origin)
  return origin_;
}
inline ::google::protobuf::RepeatedField< float >*
GridMap::mutable_origin() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.origin)
  return &origin_;
}

// repeated float orientation = 9;
inline int GridMap::orientation_size() const {
  return orientation_.size();
}
inline void GridMap::clear_orientation() {
  orientation_.Clear();
}
inline float GridMap::orientation(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.orientation)
  return orientation_.Get(index);
}
inline void GridMap::set_orientation(int index, float value) {
  orientation_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.orientation)
}
inline void GridMap::add_orientation(float value) {
  orientation_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.orientation)
}
inline const ::google::protobuf::RepeatedField< float >&
GridMap::orientation() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.orientation)
  return orientation_;
}
inline ::google::protobuf::RepeatedField< float >*
GridMap::mutable_orientation() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.orientation)
  return &orientation_;
}

// repeated float grids = 10;
inline int GridMap::grids_size() const {
  return grids_.size();
}
inline void GridMap::clear_grids() {
  grids_.Clear();
}
inline float GridMap::grids(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.GridMap.grids)
  return grids_.Get(index);
}
inline void GridMap::set_grids(int index, float value) {
  grids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.GridMap.grids)
}
inline void GridMap::add_grids(float value) {
  grids_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.GridMap.grids)
}
inline const ::google::protobuf::RepeatedField< float >&
GridMap::grids() const {
  // @@protoc_insertion_point(field_list:Proto_msg.GridMap.grids)
  return grids_;
}
inline ::google::protobuf::RepeatedField< float >*
GridMap::mutable_grids() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.GridMap.grids)
  return &grids_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_5fmsg_2eGridMap_2eproto__INCLUDED
