// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.VehicleState.proto

#ifndef PROTOBUF_Proto_5fmsg_2eVehicleState_2eproto__INCLUDED
#define PROTOBUF_Proto_5fmsg_2eVehicleState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Proto_msg {
class VehicleState;
class VehicleStateDefaultTypeInternal;
extern VehicleStateDefaultTypeInternal _VehicleState_default_instance_;
}  // namespace Proto_msg

namespace Proto_msg {

namespace protobuf_Proto_5fmsg_2eVehicleState_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Proto_5fmsg_2eVehicleState_2eproto

// ===================================================================

class VehicleState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Proto_msg.VehicleState) */ {
 public:
  VehicleState();
  virtual ~VehicleState();

  VehicleState(const VehicleState& from);

  inline VehicleState& operator=(const VehicleState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VehicleState(VehicleState&& from) noexcept
    : VehicleState() {
    *this = ::std::move(from);
  }

  inline VehicleState& operator=(VehicleState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VehicleState& default_instance();

  static inline const VehicleState* internal_default_instance() {
    return reinterpret_cast<const VehicleState*>(
               &_VehicleState_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(VehicleState* other);
  friend void swap(VehicleState& a, VehicleState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VehicleState* New() const PROTOBUF_FINAL { return New(NULL); }

  VehicleState* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VehicleState& from);
  void MergeFrom(const VehicleState& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VehicleState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double origin = 6;
  int origin_size() const;
  void clear_origin();
  static const int kOriginFieldNumber = 6;
  double origin(int index) const;
  void set_origin(int index, double value);
  void add_origin(double value);
  const ::google::protobuf::RepeatedField< double >&
      origin() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_origin();

  // repeated double pos = 7;
  int pos_size() const;
  void clear_pos();
  static const int kPosFieldNumber = 7;
  double pos(int index) const;
  void set_pos(int index, double value);
  void add_pos(double value);
  const ::google::protobuf::RepeatedField< double >&
      pos() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_pos();

  // repeated double pos_cov = 8;
  int pos_cov_size() const;
  void clear_pos_cov();
  static const int kPosCovFieldNumber = 8;
  double pos_cov(int index) const;
  void set_pos_cov(int index, double value);
  void add_pos_cov(double value);
  const ::google::protobuf::RepeatedField< double >&
      pos_cov() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_pos_cov();

  // repeated double orien = 9;
  int orien_size() const;
  void clear_orien();
  static const int kOrienFieldNumber = 9;
  double orien(int index) const;
  void set_orien(int index, double value);
  void add_orien(double value);
  const ::google::protobuf::RepeatedField< double >&
      orien() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_orien();

  // repeated double orien_cov = 10;
  int orien_cov_size() const;
  void clear_orien_cov();
  static const int kOrienCovFieldNumber = 10;
  double orien_cov(int index) const;
  void set_orien_cov(int index, double value);
  void add_orien_cov(double value);
  const ::google::protobuf::RepeatedField< double >&
      orien_cov() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_orien_cov();

  // repeated double angular_vel = 11;
  int angular_vel_size() const;
  void clear_angular_vel();
  static const int kAngularVelFieldNumber = 11;
  double angular_vel(int index) const;
  void set_angular_vel(int index, double value);
  void add_angular_vel(double value);
  const ::google::protobuf::RepeatedField< double >&
      angular_vel() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_angular_vel();

  // repeated double angular_vel_cov = 12;
  int angular_vel_cov_size() const;
  void clear_angular_vel_cov();
  static const int kAngularVelCovFieldNumber = 12;
  double angular_vel_cov(int index) const;
  void set_angular_vel_cov(int index, double value);
  void add_angular_vel_cov(double value);
  const ::google::protobuf::RepeatedField< double >&
      angular_vel_cov() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_angular_vel_cov();

  // repeated double linear_vel = 13;
  int linear_vel_size() const;
  void clear_linear_vel();
  static const int kLinearVelFieldNumber = 13;
  double linear_vel(int index) const;
  void set_linear_vel(int index, double value);
  void add_linear_vel(double value);
  const ::google::protobuf::RepeatedField< double >&
      linear_vel() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_linear_vel();

  // repeated double linear_vel_cov = 14;
  int linear_vel_cov_size() const;
  void clear_linear_vel_cov();
  static const int kLinearVelCovFieldNumber = 14;
  double linear_vel_cov(int index) const;
  void set_linear_vel_cov(int index, double value);
  void add_linear_vel_cov(double value);
  const ::google::protobuf::RepeatedField< double >&
      linear_vel_cov() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_linear_vel_cov();

  // repeated double acc = 15;
  int acc_size() const;
  void clear_acc();
  static const int kAccFieldNumber = 15;
  double acc(int index) const;
  void set_acc(int index, double value);
  void add_acc(double value);
  const ::google::protobuf::RepeatedField< double >&
      acc() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_acc();

  // repeated double acc_cov = 16;
  int acc_cov_size() const;
  void clear_acc_cov();
  static const int kAccCovFieldNumber = 16;
  double acc_cov(int index) const;
  void set_acc_cov(int index, double value);
  void add_acc_cov(double value);
  const ::google::protobuf::RepeatedField< double >&
      acc_cov() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_acc_cov();

  // optional string parent_frame_id = 3;
  bool has_parent_frame_id() const;
  void clear_parent_frame_id();
  static const int kParentFrameIdFieldNumber = 3;
  const ::std::string& parent_frame_id() const;
  void set_parent_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_parent_frame_id(::std::string&& value);
  #endif
  void set_parent_frame_id(const char* value);
  void set_parent_frame_id(const char* value, size_t size);
  ::std::string* mutable_parent_frame_id();
  ::std::string* release_parent_frame_id();
  void set_allocated_parent_frame_id(::std::string* parent_frame_id);

  // optional string frame_id = 4;
  bool has_frame_id() const;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 4;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);

  // optional double timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // optional uint32 seq = 2;
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 2;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // optional uint32 status = 5;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 5;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Proto_msg.VehicleState)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_seq();
  void clear_has_seq();
  void set_has_parent_frame_id();
  void clear_has_parent_frame_id();
  void set_has_frame_id();
  void clear_has_frame_id();
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > origin_;
  ::google::protobuf::RepeatedField< double > pos_;
  ::google::protobuf::RepeatedField< double > pos_cov_;
  ::google::protobuf::RepeatedField< double > orien_;
  ::google::protobuf::RepeatedField< double > orien_cov_;
  ::google::protobuf::RepeatedField< double > angular_vel_;
  ::google::protobuf::RepeatedField< double > angular_vel_cov_;
  ::google::protobuf::RepeatedField< double > linear_vel_;
  ::google::protobuf::RepeatedField< double > linear_vel_cov_;
  ::google::protobuf::RepeatedField< double > acc_;
  ::google::protobuf::RepeatedField< double > acc_cov_;
  ::google::protobuf::internal::ArenaStringPtr parent_frame_id_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  double timestamp_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 status_;
  friend struct protobuf_Proto_5fmsg_2eVehicleState_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VehicleState

// optional double timestamp = 1;
inline bool VehicleState::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void VehicleState::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void VehicleState::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void VehicleState::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double VehicleState::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.timestamp)
  return timestamp_;
}
inline void VehicleState::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.timestamp)
}

// optional uint32 seq = 2;
inline bool VehicleState::has_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void VehicleState::set_has_seq() {
  _has_bits_[0] |= 0x00000008u;
}
inline void VehicleState::clear_has_seq() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void VehicleState::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 VehicleState::seq() const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.seq)
  return seq_;
}
inline void VehicleState::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.seq)
}

// optional string parent_frame_id = 3;
inline bool VehicleState::has_parent_frame_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VehicleState::set_has_parent_frame_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VehicleState::clear_has_parent_frame_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VehicleState::clear_parent_frame_id() {
  parent_frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parent_frame_id();
}
inline const ::std::string& VehicleState::parent_frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.parent_frame_id)
  return parent_frame_id_.GetNoArena();
}
inline void VehicleState::set_parent_frame_id(const ::std::string& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.parent_frame_id)
}
#if LANG_CXX11
inline void VehicleState::set_parent_frame_id(::std::string&& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.VehicleState.parent_frame_id)
}
#endif
inline void VehicleState::set_parent_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.VehicleState.parent_frame_id)
}
inline void VehicleState::set_parent_frame_id(const char* value, size_t size) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.VehicleState.parent_frame_id)
}
inline ::std::string* VehicleState::mutable_parent_frame_id() {
  set_has_parent_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.VehicleState.parent_frame_id)
  return parent_frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VehicleState::release_parent_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.VehicleState.parent_frame_id)
  clear_has_parent_frame_id();
  return parent_frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VehicleState::set_allocated_parent_frame_id(::std::string* parent_frame_id) {
  if (parent_frame_id != NULL) {
    set_has_parent_frame_id();
  } else {
    clear_has_parent_frame_id();
  }
  parent_frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent_frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.VehicleState.parent_frame_id)
}

// optional string frame_id = 4;
inline bool VehicleState::has_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VehicleState::set_has_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VehicleState::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VehicleState::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_frame_id();
}
inline const ::std::string& VehicleState::frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.frame_id)
  return frame_id_.GetNoArena();
}
inline void VehicleState::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.frame_id)
}
#if LANG_CXX11
inline void VehicleState::set_frame_id(::std::string&& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.VehicleState.frame_id)
}
#endif
inline void VehicleState::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.VehicleState.frame_id)
}
inline void VehicleState::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.VehicleState.frame_id)
}
inline ::std::string* VehicleState::mutable_frame_id() {
  set_has_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.VehicleState.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VehicleState::release_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.VehicleState.frame_id)
  clear_has_frame_id();
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VehicleState::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    set_has_frame_id();
  } else {
    clear_has_frame_id();
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.VehicleState.frame_id)
}

// optional uint32 status = 5;
inline bool VehicleState::has_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void VehicleState::set_has_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void VehicleState::clear_has_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void VehicleState::clear_status() {
  status_ = 0u;
  clear_has_status();
}
inline ::google::protobuf::uint32 VehicleState::status() const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.status)
  return status_;
}
inline void VehicleState::set_status(::google::protobuf::uint32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.status)
}

// repeated double origin = 6;
inline int VehicleState::origin_size() const {
  return origin_.size();
}
inline void VehicleState::clear_origin() {
  origin_.Clear();
}
inline double VehicleState::origin(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.origin)
  return origin_.Get(index);
}
inline void VehicleState::set_origin(int index, double value) {
  origin_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.origin)
}
inline void VehicleState::add_origin(double value) {
  origin_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.origin)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::origin() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.origin)
  return origin_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_origin() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.origin)
  return &origin_;
}

// repeated double pos = 7;
inline int VehicleState::pos_size() const {
  return pos_.size();
}
inline void VehicleState::clear_pos() {
  pos_.Clear();
}
inline double VehicleState::pos(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.pos)
  return pos_.Get(index);
}
inline void VehicleState::set_pos(int index, double value) {
  pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.pos)
}
inline void VehicleState::add_pos(double value) {
  pos_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.pos)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::pos() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.pos)
  return pos_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_pos() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.pos)
  return &pos_;
}

// repeated double pos_cov = 8;
inline int VehicleState::pos_cov_size() const {
  return pos_cov_.size();
}
inline void VehicleState::clear_pos_cov() {
  pos_cov_.Clear();
}
inline double VehicleState::pos_cov(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.pos_cov)
  return pos_cov_.Get(index);
}
inline void VehicleState::set_pos_cov(int index, double value) {
  pos_cov_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.pos_cov)
}
inline void VehicleState::add_pos_cov(double value) {
  pos_cov_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.pos_cov)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::pos_cov() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.pos_cov)
  return pos_cov_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_pos_cov() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.pos_cov)
  return &pos_cov_;
}

// repeated double orien = 9;
inline int VehicleState::orien_size() const {
  return orien_.size();
}
inline void VehicleState::clear_orien() {
  orien_.Clear();
}
inline double VehicleState::orien(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.orien)
  return orien_.Get(index);
}
inline void VehicleState::set_orien(int index, double value) {
  orien_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.orien)
}
inline void VehicleState::add_orien(double value) {
  orien_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.orien)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::orien() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.orien)
  return orien_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_orien() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.orien)
  return &orien_;
}

// repeated double orien_cov = 10;
inline int VehicleState::orien_cov_size() const {
  return orien_cov_.size();
}
inline void VehicleState::clear_orien_cov() {
  orien_cov_.Clear();
}
inline double VehicleState::orien_cov(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.orien_cov)
  return orien_cov_.Get(index);
}
inline void VehicleState::set_orien_cov(int index, double value) {
  orien_cov_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.orien_cov)
}
inline void VehicleState::add_orien_cov(double value) {
  orien_cov_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.orien_cov)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::orien_cov() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.orien_cov)
  return orien_cov_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_orien_cov() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.orien_cov)
  return &orien_cov_;
}

// repeated double angular_vel = 11;
inline int VehicleState::angular_vel_size() const {
  return angular_vel_.size();
}
inline void VehicleState::clear_angular_vel() {
  angular_vel_.Clear();
}
inline double VehicleState::angular_vel(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.angular_vel)
  return angular_vel_.Get(index);
}
inline void VehicleState::set_angular_vel(int index, double value) {
  angular_vel_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.angular_vel)
}
inline void VehicleState::add_angular_vel(double value) {
  angular_vel_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.angular_vel)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::angular_vel() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.angular_vel)
  return angular_vel_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_angular_vel() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.angular_vel)
  return &angular_vel_;
}

// repeated double angular_vel_cov = 12;
inline int VehicleState::angular_vel_cov_size() const {
  return angular_vel_cov_.size();
}
inline void VehicleState::clear_angular_vel_cov() {
  angular_vel_cov_.Clear();
}
inline double VehicleState::angular_vel_cov(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.angular_vel_cov)
  return angular_vel_cov_.Get(index);
}
inline void VehicleState::set_angular_vel_cov(int index, double value) {
  angular_vel_cov_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.angular_vel_cov)
}
inline void VehicleState::add_angular_vel_cov(double value) {
  angular_vel_cov_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.angular_vel_cov)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::angular_vel_cov() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.angular_vel_cov)
  return angular_vel_cov_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_angular_vel_cov() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.angular_vel_cov)
  return &angular_vel_cov_;
}

// repeated double linear_vel = 13;
inline int VehicleState::linear_vel_size() const {
  return linear_vel_.size();
}
inline void VehicleState::clear_linear_vel() {
  linear_vel_.Clear();
}
inline double VehicleState::linear_vel(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.linear_vel)
  return linear_vel_.Get(index);
}
inline void VehicleState::set_linear_vel(int index, double value) {
  linear_vel_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.linear_vel)
}
inline void VehicleState::add_linear_vel(double value) {
  linear_vel_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.linear_vel)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::linear_vel() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.linear_vel)
  return linear_vel_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_linear_vel() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.linear_vel)
  return &linear_vel_;
}

// repeated double linear_vel_cov = 14;
inline int VehicleState::linear_vel_cov_size() const {
  return linear_vel_cov_.size();
}
inline void VehicleState::clear_linear_vel_cov() {
  linear_vel_cov_.Clear();
}
inline double VehicleState::linear_vel_cov(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.linear_vel_cov)
  return linear_vel_cov_.Get(index);
}
inline void VehicleState::set_linear_vel_cov(int index, double value) {
  linear_vel_cov_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.linear_vel_cov)
}
inline void VehicleState::add_linear_vel_cov(double value) {
  linear_vel_cov_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.linear_vel_cov)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::linear_vel_cov() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.linear_vel_cov)
  return linear_vel_cov_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_linear_vel_cov() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.linear_vel_cov)
  return &linear_vel_cov_;
}

// repeated double acc = 15;
inline int VehicleState::acc_size() const {
  return acc_.size();
}
inline void VehicleState::clear_acc() {
  acc_.Clear();
}
inline double VehicleState::acc(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.acc)
  return acc_.Get(index);
}
inline void VehicleState::set_acc(int index, double value) {
  acc_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.acc)
}
inline void VehicleState::add_acc(double value) {
  acc_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.acc)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::acc() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.acc)
  return acc_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_acc() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.acc)
  return &acc_;
}

// repeated double acc_cov = 16;
inline int VehicleState::acc_cov_size() const {
  return acc_cov_.size();
}
inline void VehicleState::clear_acc_cov() {
  acc_cov_.Clear();
}
inline double VehicleState::acc_cov(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.VehicleState.acc_cov)
  return acc_cov_.Get(index);
}
inline void VehicleState::set_acc_cov(int index, double value) {
  acc_cov_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.VehicleState.acc_cov)
}
inline void VehicleState::add_acc_cov(double value) {
  acc_cov_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.VehicleState.acc_cov)
}
inline const ::google::protobuf::RepeatedField< double >&
VehicleState::acc_cov() const {
  // @@protoc_insertion_point(field_list:Proto_msg.VehicleState.acc_cov)
  return acc_cov_;
}
inline ::google::protobuf::RepeatedField< double >*
VehicleState::mutable_acc_cov() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.VehicleState.acc_cov)
  return &acc_cov_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace Proto_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_5fmsg_2eVehicleState_2eproto__INCLUDED
