// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.LidarPoints.proto

#ifndef PROTOBUF_Proto_5fmsg_2eLidarPoints_2eproto__INCLUDED
#define PROTOBUF_Proto_5fmsg_2eLidarPoints_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Proto_msg {
class LidarPoints;
class LidarPointsDefaultTypeInternal;
extern LidarPointsDefaultTypeInternal _LidarPoints_default_instance_;
}  // namespace Proto_msg

namespace Proto_msg {

namespace protobuf_Proto_5fmsg_2eLidarPoints_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Proto_5fmsg_2eLidarPoints_2eproto

// ===================================================================

class LidarPoints : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Proto_msg.LidarPoints) */ {
 public:
  LidarPoints();
  virtual ~LidarPoints();

  LidarPoints(const LidarPoints& from);

  inline LidarPoints& operator=(const LidarPoints& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LidarPoints(LidarPoints&& from) noexcept
    : LidarPoints() {
    *this = ::std::move(from);
  }

  inline LidarPoints& operator=(LidarPoints&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarPoints& default_instance();

  static inline const LidarPoints* internal_default_instance() {
    return reinterpret_cast<const LidarPoints*>(
               &_LidarPoints_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LidarPoints* other);
  friend void swap(LidarPoints& a, LidarPoints& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LidarPoints* New() const PROTOBUF_FINAL { return New(NULL); }

  LidarPoints* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LidarPoints& from);
  void MergeFrom(const LidarPoints& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LidarPoints* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float data = 12;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 12;
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::google::protobuf::RepeatedField< float >&
      data() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_data();

  // optional string parent_frame_id = 3;
  bool has_parent_frame_id() const;
  void clear_parent_frame_id();
  static const int kParentFrameIdFieldNumber = 3;
  const ::std::string& parent_frame_id() const;
  void set_parent_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_parent_frame_id(::std::string&& value);
  #endif
  void set_parent_frame_id(const char* value);
  void set_parent_frame_id(const char* value, size_t size);
  ::std::string* mutable_parent_frame_id();
  ::std::string* release_parent_frame_id();
  void set_allocated_parent_frame_id(::std::string* parent_frame_id);

  // optional string frame_id = 4;
  bool has_frame_id() const;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 4;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);

  // optional string lidar_model = 10;
  bool has_lidar_model() const;
  void clear_lidar_model();
  static const int kLidarModelFieldNumber = 10;
  const ::std::string& lidar_model() const;
  void set_lidar_model(const ::std::string& value);
  #if LANG_CXX11
  void set_lidar_model(::std::string&& value);
  #endif
  void set_lidar_model(const char* value);
  void set_lidar_model(const char* value, size_t size);
  ::std::string* mutable_lidar_model();
  ::std::string* release_lidar_model();
  void set_allocated_lidar_model(::std::string* lidar_model);

  // optional string points_type = 11;
  bool has_points_type() const;
  void clear_points_type();
  static const int kPointsTypeFieldNumber = 11;
  const ::std::string& points_type() const;
  void set_points_type(const ::std::string& value);
  #if LANG_CXX11
  void set_points_type(::std::string&& value);
  #endif
  void set_points_type(const char* value);
  void set_points_type(const char* value, size_t size);
  ::std::string* mutable_points_type();
  ::std::string* release_points_type();
  void set_allocated_points_type(::std::string* points_type);

  // optional double timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // optional uint32 seq = 2;
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 2;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // optional uint32 height = 6;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 6;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // optional uint32 width = 7;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 7;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // optional bool motion_correct = 5;
  bool has_motion_correct() const;
  void clear_motion_correct();
  static const int kMotionCorrectFieldNumber = 5;
  bool motion_correct() const;
  void set_motion_correct(bool value);

  // optional bool is_dense = 8;
  bool has_is_dense() const;
  void clear_is_dense();
  static const int kIsDenseFieldNumber = 8;
  bool is_dense() const;
  void set_is_dense(bool value);

  // optional bool is_transform = 9;
  bool has_is_transform() const;
  void clear_is_transform();
  static const int kIsTransformFieldNumber = 9;
  bool is_transform() const;
  void set_is_transform(bool value);

  // @@protoc_insertion_point(class_scope:Proto_msg.LidarPoints)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_seq();
  void clear_has_seq();
  void set_has_parent_frame_id();
  void clear_has_parent_frame_id();
  void set_has_frame_id();
  void clear_has_frame_id();
  void set_has_motion_correct();
  void clear_has_motion_correct();
  void set_has_height();
  void clear_has_height();
  void set_has_width();
  void clear_has_width();
  void set_has_is_dense();
  void clear_has_is_dense();
  void set_has_is_transform();
  void clear_has_is_transform();
  void set_has_lidar_model();
  void clear_has_lidar_model();
  void set_has_points_type();
  void clear_has_points_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > data_;
  ::google::protobuf::internal::ArenaStringPtr parent_frame_id_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  ::google::protobuf::internal::ArenaStringPtr lidar_model_;
  ::google::protobuf::internal::ArenaStringPtr points_type_;
  double timestamp_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::uint32 width_;
  bool motion_correct_;
  bool is_dense_;
  bool is_transform_;
  friend struct protobuf_Proto_5fmsg_2eLidarPoints_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LidarPoints

// optional double timestamp = 1;
inline bool LidarPoints::has_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LidarPoints::set_has_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LidarPoints::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LidarPoints::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double LidarPoints::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.timestamp)
  return timestamp_;
}
inline void LidarPoints::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.timestamp)
}

// optional uint32 seq = 2;
inline bool LidarPoints::has_seq() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LidarPoints::set_has_seq() {
  _has_bits_[0] |= 0x00000020u;
}
inline void LidarPoints::clear_has_seq() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void LidarPoints::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 LidarPoints::seq() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.seq)
  return seq_;
}
inline void LidarPoints::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.seq)
}

// optional string parent_frame_id = 3;
inline bool LidarPoints::has_parent_frame_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LidarPoints::set_has_parent_frame_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LidarPoints::clear_has_parent_frame_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LidarPoints::clear_parent_frame_id() {
  parent_frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parent_frame_id();
}
inline const ::std::string& LidarPoints::parent_frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.parent_frame_id)
  return parent_frame_id_.GetNoArena();
}
inline void LidarPoints::set_parent_frame_id(const ::std::string& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.parent_frame_id)
}
#if LANG_CXX11
inline void LidarPoints::set_parent_frame_id(::std::string&& value) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.LidarPoints.parent_frame_id)
}
#endif
inline void LidarPoints::set_parent_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarPoints.parent_frame_id)
}
inline void LidarPoints::set_parent_frame_id(const char* value, size_t size) {
  set_has_parent_frame_id();
  parent_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarPoints.parent_frame_id)
}
inline ::std::string* LidarPoints::mutable_parent_frame_id() {
  set_has_parent_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarPoints.parent_frame_id)
  return parent_frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarPoints::release_parent_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.LidarPoints.parent_frame_id)
  clear_has_parent_frame_id();
  return parent_frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarPoints::set_allocated_parent_frame_id(::std::string* parent_frame_id) {
  if (parent_frame_id != NULL) {
    set_has_parent_frame_id();
  } else {
    clear_has_parent_frame_id();
  }
  parent_frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent_frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.LidarPoints.parent_frame_id)
}

// optional string frame_id = 4;
inline bool LidarPoints::has_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LidarPoints::set_has_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LidarPoints::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LidarPoints::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_frame_id();
}
inline const ::std::string& LidarPoints::frame_id() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.frame_id)
  return frame_id_.GetNoArena();
}
inline void LidarPoints::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.frame_id)
}
#if LANG_CXX11
inline void LidarPoints::set_frame_id(::std::string&& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.LidarPoints.frame_id)
}
#endif
inline void LidarPoints::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarPoints.frame_id)
}
inline void LidarPoints::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarPoints.frame_id)
}
inline ::std::string* LidarPoints::mutable_frame_id() {
  set_has_frame_id();
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarPoints.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarPoints::release_frame_id() {
  // @@protoc_insertion_point(field_release:Proto_msg.LidarPoints.frame_id)
  clear_has_frame_id();
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarPoints::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    set_has_frame_id();
  } else {
    clear_has_frame_id();
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.LidarPoints.frame_id)
}

// optional bool motion_correct = 5;
inline bool LidarPoints::has_motion_correct() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void LidarPoints::set_has_motion_correct() {
  _has_bits_[0] |= 0x00000100u;
}
inline void LidarPoints::clear_has_motion_correct() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void LidarPoints::clear_motion_correct() {
  motion_correct_ = false;
  clear_has_motion_correct();
}
inline bool LidarPoints::motion_correct() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.motion_correct)
  return motion_correct_;
}
inline void LidarPoints::set_motion_correct(bool value) {
  set_has_motion_correct();
  motion_correct_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.motion_correct)
}

// optional uint32 height = 6;
inline bool LidarPoints::has_height() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void LidarPoints::set_has_height() {
  _has_bits_[0] |= 0x00000040u;
}
inline void LidarPoints::clear_has_height() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void LidarPoints::clear_height() {
  height_ = 0u;
  clear_has_height();
}
inline ::google::protobuf::uint32 LidarPoints::height() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.height)
  return height_;
}
inline void LidarPoints::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.height)
}

// optional uint32 width = 7;
inline bool LidarPoints::has_width() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void LidarPoints::set_has_width() {
  _has_bits_[0] |= 0x00000080u;
}
inline void LidarPoints::clear_has_width() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void LidarPoints::clear_width() {
  width_ = 0u;
  clear_has_width();
}
inline ::google::protobuf::uint32 LidarPoints::width() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.width)
  return width_;
}
inline void LidarPoints::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.width)
}

// optional bool is_dense = 8;
inline bool LidarPoints::has_is_dense() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void LidarPoints::set_has_is_dense() {
  _has_bits_[0] |= 0x00000200u;
}
inline void LidarPoints::clear_has_is_dense() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void LidarPoints::clear_is_dense() {
  is_dense_ = false;
  clear_has_is_dense();
}
inline bool LidarPoints::is_dense() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.is_dense)
  return is_dense_;
}
inline void LidarPoints::set_is_dense(bool value) {
  set_has_is_dense();
  is_dense_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.is_dense)
}

// optional bool is_transform = 9;
inline bool LidarPoints::has_is_transform() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void LidarPoints::set_has_is_transform() {
  _has_bits_[0] |= 0x00000400u;
}
inline void LidarPoints::clear_has_is_transform() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void LidarPoints::clear_is_transform() {
  is_transform_ = false;
  clear_has_is_transform();
}
inline bool LidarPoints::is_transform() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.is_transform)
  return is_transform_;
}
inline void LidarPoints::set_is_transform(bool value) {
  set_has_is_transform();
  is_transform_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.is_transform)
}

// optional string lidar_model = 10;
inline bool LidarPoints::has_lidar_model() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LidarPoints::set_has_lidar_model() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LidarPoints::clear_has_lidar_model() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LidarPoints::clear_lidar_model() {
  lidar_model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_lidar_model();
}
inline const ::std::string& LidarPoints::lidar_model() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.lidar_model)
  return lidar_model_.GetNoArena();
}
inline void LidarPoints::set_lidar_model(const ::std::string& value) {
  set_has_lidar_model();
  lidar_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.lidar_model)
}
#if LANG_CXX11
inline void LidarPoints::set_lidar_model(::std::string&& value) {
  set_has_lidar_model();
  lidar_model_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.LidarPoints.lidar_model)
}
#endif
inline void LidarPoints::set_lidar_model(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_lidar_model();
  lidar_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarPoints.lidar_model)
}
inline void LidarPoints::set_lidar_model(const char* value, size_t size) {
  set_has_lidar_model();
  lidar_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarPoints.lidar_model)
}
inline ::std::string* LidarPoints::mutable_lidar_model() {
  set_has_lidar_model();
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarPoints.lidar_model)
  return lidar_model_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarPoints::release_lidar_model() {
  // @@protoc_insertion_point(field_release:Proto_msg.LidarPoints.lidar_model)
  clear_has_lidar_model();
  return lidar_model_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarPoints::set_allocated_lidar_model(::std::string* lidar_model) {
  if (lidar_model != NULL) {
    set_has_lidar_model();
  } else {
    clear_has_lidar_model();
  }
  lidar_model_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), lidar_model);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.LidarPoints.lidar_model)
}

// optional string points_type = 11;
inline bool LidarPoints::has_points_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LidarPoints::set_has_points_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LidarPoints::clear_has_points_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LidarPoints::clear_points_type() {
  points_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_points_type();
}
inline const ::std::string& LidarPoints::points_type() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.points_type)
  return points_type_.GetNoArena();
}
inline void LidarPoints::set_points_type(const ::std::string& value) {
  set_has_points_type();
  points_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.points_type)
}
#if LANG_CXX11
inline void LidarPoints::set_points_type(::std::string&& value) {
  set_has_points_type();
  points_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto_msg.LidarPoints.points_type)
}
#endif
inline void LidarPoints::set_points_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_points_type();
  points_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarPoints.points_type)
}
inline void LidarPoints::set_points_type(const char* value, size_t size) {
  set_has_points_type();
  points_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarPoints.points_type)
}
inline ::std::string* LidarPoints::mutable_points_type() {
  set_has_points_type();
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarPoints.points_type)
  return points_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarPoints::release_points_type() {
  // @@protoc_insertion_point(field_release:Proto_msg.LidarPoints.points_type)
  clear_has_points_type();
  return points_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarPoints::set_allocated_points_type(::std::string* points_type) {
  if (points_type != NULL) {
    set_has_points_type();
  } else {
    clear_has_points_type();
  }
  points_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), points_type);
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.LidarPoints.points_type)
}

// repeated float data = 12;
inline int LidarPoints::data_size() const {
  return data_.size();
}
inline void LidarPoints::clear_data() {
  data_.Clear();
}
inline float LidarPoints::data(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPoints.data)
  return data_.Get(index);
}
inline void LidarPoints::set_data(int index, float value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPoints.data)
}
inline void LidarPoints::add_data(float value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:Proto_msg.LidarPoints.data)
}
inline const ::google::protobuf::RepeatedField< float >&
LidarPoints::data() const {
  // @@protoc_insertion_point(field_list:Proto_msg.LidarPoints.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< float >*
LidarPoints::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.LidarPoints.data)
  return &data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace Proto_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_5fmsg_2eLidarPoints_2eproto__INCLUDED
