// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.Gnss.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Proto_msg.Gnss.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Proto_msg {

namespace {

const ::google::protobuf::Descriptor* Gnss_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Gnss_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Proto_5fmsg_2eGnss_2eproto() {
  protobuf_AddDesc_Proto_5fmsg_2eGnss_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Proto_msg.Gnss.proto");
  GOOGLE_CHECK(file != NULL);
  Gnss_descriptor_ = file->message_type(0);
  static const int Gnss_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, seq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, parent_frame_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, frame_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, sat_cnt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, pos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, pos_cov_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, orien_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, oeirn_cov_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, linear_vel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, linear_vel_cov_),
  };
  Gnss_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Gnss_descriptor_,
      Gnss::default_instance_,
      Gnss_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Gnss, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Gnss));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Proto_5fmsg_2eGnss_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Gnss_descriptor_, &Gnss::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Proto_5fmsg_2eGnss_2eproto() {
  delete Gnss::default_instance_;
  delete Gnss_reflection_;
}

void protobuf_AddDesc_Proto_5fmsg_2eGnss_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024Proto_msg.Gnss.proto\022\tProto_msg\"\354\001\n\004Gn"
    "ss\022\021\n\ttimestamp\030\001 \001(\001\022\013\n\003seq\030\002 \001(\r\022\027\n\017pa"
    "rent_frame_id\030\003 \001(\t\022\020\n\010frame_id\030\004 \001(\t\022\016\n"
    "\006status\030\005 \001(\r\022\014\n\004type\030\006 \001(\r\022\017\n\007sat_cnt\030\007"
    " \001(\r\022\013\n\003pos\030\010 \003(\001\022\017\n\007pos_cov\030\t \003(\001\022\r\n\005or"
    "ien\030\n \003(\001\022\021\n\toeirn_cov\030\013 \003(\001\022\022\n\nlinear_v"
    "el\030\014 \003(\001\022\026\n\016linear_vel_cov\030\r \003(\001", 272);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto_msg.Gnss.proto", &protobuf_RegisterTypes);
  Gnss::default_instance_ = new Gnss();
  Gnss::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Proto_5fmsg_2eGnss_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Proto_5fmsg_2eGnss_2eproto {
  StaticDescriptorInitializer_Proto_5fmsg_2eGnss_2eproto() {
    protobuf_AddDesc_Proto_5fmsg_2eGnss_2eproto();
  }
} static_descriptor_initializer_Proto_5fmsg_2eGnss_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Gnss::kTimestampFieldNumber;
const int Gnss::kSeqFieldNumber;
const int Gnss::kParentFrameIdFieldNumber;
const int Gnss::kFrameIdFieldNumber;
const int Gnss::kStatusFieldNumber;
const int Gnss::kTypeFieldNumber;
const int Gnss::kSatCntFieldNumber;
const int Gnss::kPosFieldNumber;
const int Gnss::kPosCovFieldNumber;
const int Gnss::kOrienFieldNumber;
const int Gnss::kOeirnCovFieldNumber;
const int Gnss::kLinearVelFieldNumber;
const int Gnss::kLinearVelCovFieldNumber;
#endif  // !_MSC_VER

Gnss::Gnss()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Proto_msg.Gnss)
}

void Gnss::InitAsDefaultInstance() {
}

Gnss::Gnss(const Gnss& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Proto_msg.Gnss)
}

void Gnss::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  timestamp_ = 0;
  seq_ = 0u;
  parent_frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0u;
  type_ = 0u;
  sat_cnt_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Gnss::~Gnss() {
  // @@protoc_insertion_point(destructor:Proto_msg.Gnss)
  SharedDtor();
}

void Gnss::SharedDtor() {
  if (parent_frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete parent_frame_id_;
  }
  if (frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete frame_id_;
  }
  if (this != default_instance_) {
  }
}

void Gnss::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Gnss::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Gnss_descriptor_;
}

const Gnss& Gnss::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Proto_5fmsg_2eGnss_2eproto();
  return *default_instance_;
}

Gnss* Gnss::default_instance_ = NULL;

Gnss* Gnss::New() const {
  return new Gnss;
}

void Gnss::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Gnss*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 127) {
    ZR_(seq_, status_);
    ZR_(type_, sat_cnt_);
    timestamp_ = 0;
    if (has_parent_frame_id()) {
      if (parent_frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        parent_frame_id_->clear();
      }
    }
    if (has_frame_id()) {
      if (frame_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        frame_id_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  pos_.Clear();
  pos_cov_.Clear();
  orien_.Clear();
  oeirn_cov_.Clear();
  linear_vel_.Clear();
  linear_vel_cov_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Gnss::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Proto_msg.Gnss)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double timestamp = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_seq;
        break;
      }

      // optional uint32 seq = 2;
      case 2: {
        if (tag == 16) {
         parse_seq:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seq_)));
          set_has_seq();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_parent_frame_id;
        break;
      }

      // optional string parent_frame_id = 3;
      case 3: {
        if (tag == 26) {
         parse_parent_frame_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parent_frame_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parent_frame_id().data(), this->parent_frame_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "parent_frame_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_frame_id;
        break;
      }

      // optional string frame_id = 4;
      case 4: {
        if (tag == 34) {
         parse_frame_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_frame_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->frame_id().data(), this->frame_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "frame_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_status;
        break;
      }

      // optional uint32 status = 5;
      case 5: {
        if (tag == 40) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &status_)));
          set_has_status();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_type;
        break;
      }

      // optional uint32 type = 6;
      case 6: {
        if (tag == 48) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_sat_cnt;
        break;
      }

      // optional uint32 sat_cnt = 7;
      case 7: {
        if (tag == 56) {
         parse_sat_cnt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sat_cnt_)));
          set_has_sat_cnt();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_pos;
        break;
      }

      // repeated double pos = 8;
      case 8: {
        if (tag == 65) {
         parse_pos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 65, input, this->mutable_pos())));
        } else if (tag == 66) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_pos())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_pos;
        if (input->ExpectTag(73)) goto parse_pos_cov;
        break;
      }

      // repeated double pos_cov = 9;
      case 9: {
        if (tag == 73) {
         parse_pos_cov:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 73, input, this->mutable_pos_cov())));
        } else if (tag == 74) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_pos_cov())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_pos_cov;
        if (input->ExpectTag(81)) goto parse_orien;
        break;
      }

      // repeated double orien = 10;
      case 10: {
        if (tag == 81) {
         parse_orien:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 81, input, this->mutable_orien())));
        } else if (tag == 82) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_orien())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_orien;
        if (input->ExpectTag(89)) goto parse_oeirn_cov;
        break;
      }

      // repeated double oeirn_cov = 11;
      case 11: {
        if (tag == 89) {
         parse_oeirn_cov:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 89, input, this->mutable_oeirn_cov())));
        } else if (tag == 90) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_oeirn_cov())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(89)) goto parse_oeirn_cov;
        if (input->ExpectTag(97)) goto parse_linear_vel;
        break;
      }

      // repeated double linear_vel = 12;
      case 12: {
        if (tag == 97) {
         parse_linear_vel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 97, input, this->mutable_linear_vel())));
        } else if (tag == 98) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_linear_vel())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(97)) goto parse_linear_vel;
        if (input->ExpectTag(105)) goto parse_linear_vel_cov;
        break;
      }

      // repeated double linear_vel_cov = 13;
      case 13: {
        if (tag == 105) {
         parse_linear_vel_cov:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 105, input, this->mutable_linear_vel_cov())));
        } else if (tag == 106) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_linear_vel_cov())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(105)) goto parse_linear_vel_cov;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Proto_msg.Gnss)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Proto_msg.Gnss)
  return false;
#undef DO_
}

void Gnss::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Proto_msg.Gnss)
  // optional double timestamp = 1;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->timestamp(), output);
  }

  // optional uint32 seq = 2;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->seq(), output);
  }

  // optional string parent_frame_id = 3;
  if (has_parent_frame_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_frame_id().data(), this->parent_frame_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "parent_frame_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->parent_frame_id(), output);
  }

  // optional string frame_id = 4;
  if (has_frame_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), this->frame_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "frame_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->frame_id(), output);
  }

  // optional uint32 status = 5;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->status(), output);
  }

  // optional uint32 type = 6;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->type(), output);
  }

  // optional uint32 sat_cnt = 7;
  if (has_sat_cnt()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->sat_cnt(), output);
  }

  // repeated double pos = 8;
  for (int i = 0; i < this->pos_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      8, this->pos(i), output);
  }

  // repeated double pos_cov = 9;
  for (int i = 0; i < this->pos_cov_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      9, this->pos_cov(i), output);
  }

  // repeated double orien = 10;
  for (int i = 0; i < this->orien_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      10, this->orien(i), output);
  }

  // repeated double oeirn_cov = 11;
  for (int i = 0; i < this->oeirn_cov_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      11, this->oeirn_cov(i), output);
  }

  // repeated double linear_vel = 12;
  for (int i = 0; i < this->linear_vel_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      12, this->linear_vel(i), output);
  }

  // repeated double linear_vel_cov = 13;
  for (int i = 0; i < this->linear_vel_cov_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      13, this->linear_vel_cov(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Proto_msg.Gnss)
}

::google::protobuf::uint8* Gnss::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto_msg.Gnss)
  // optional double timestamp = 1;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->timestamp(), target);
  }

  // optional uint32 seq = 2;
  if (has_seq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->seq(), target);
  }

  // optional string parent_frame_id = 3;
  if (has_parent_frame_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_frame_id().data(), this->parent_frame_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "parent_frame_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->parent_frame_id(), target);
  }

  // optional string frame_id = 4;
  if (has_frame_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), this->frame_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "frame_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->frame_id(), target);
  }

  // optional uint32 status = 5;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->status(), target);
  }

  // optional uint32 type = 6;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->type(), target);
  }

  // optional uint32 sat_cnt = 7;
  if (has_sat_cnt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->sat_cnt(), target);
  }

  // repeated double pos = 8;
  for (int i = 0; i < this->pos_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(8, this->pos(i), target);
  }

  // repeated double pos_cov = 9;
  for (int i = 0; i < this->pos_cov_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(9, this->pos_cov(i), target);
  }

  // repeated double orien = 10;
  for (int i = 0; i < this->orien_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(10, this->orien(i), target);
  }

  // repeated double oeirn_cov = 11;
  for (int i = 0; i < this->oeirn_cov_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(11, this->oeirn_cov(i), target);
  }

  // repeated double linear_vel = 12;
  for (int i = 0; i < this->linear_vel_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(12, this->linear_vel(i), target);
  }

  // repeated double linear_vel_cov = 13;
  for (int i = 0; i < this->linear_vel_cov_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(13, this->linear_vel_cov(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto_msg.Gnss)
  return target;
}

int Gnss::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double timestamp = 1;
    if (has_timestamp()) {
      total_size += 1 + 8;
    }

    // optional uint32 seq = 2;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->seq());
    }

    // optional string parent_frame_id = 3;
    if (has_parent_frame_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->parent_frame_id());
    }

    // optional string frame_id = 4;
    if (has_frame_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->frame_id());
    }

    // optional uint32 status = 5;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->status());
    }

    // optional uint32 type = 6;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->type());
    }

    // optional uint32 sat_cnt = 7;
    if (has_sat_cnt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->sat_cnt());
    }

  }
  // repeated double pos = 8;
  {
    int data_size = 0;
    data_size = 8 * this->pos_size();
    total_size += 1 * this->pos_size() + data_size;
  }

  // repeated double pos_cov = 9;
  {
    int data_size = 0;
    data_size = 8 * this->pos_cov_size();
    total_size += 1 * this->pos_cov_size() + data_size;
  }

  // repeated double orien = 10;
  {
    int data_size = 0;
    data_size = 8 * this->orien_size();
    total_size += 1 * this->orien_size() + data_size;
  }

  // repeated double oeirn_cov = 11;
  {
    int data_size = 0;
    data_size = 8 * this->oeirn_cov_size();
    total_size += 1 * this->oeirn_cov_size() + data_size;
  }

  // repeated double linear_vel = 12;
  {
    int data_size = 0;
    data_size = 8 * this->linear_vel_size();
    total_size += 1 * this->linear_vel_size() + data_size;
  }

  // repeated double linear_vel_cov = 13;
  {
    int data_size = 0;
    data_size = 8 * this->linear_vel_cov_size();
    total_size += 1 * this->linear_vel_cov_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Gnss::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Gnss* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Gnss*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Gnss::MergeFrom(const Gnss& from) {
  GOOGLE_CHECK_NE(&from, this);
  pos_.MergeFrom(from.pos_);
  pos_cov_.MergeFrom(from.pos_cov_);
  orien_.MergeFrom(from.orien_);
  oeirn_cov_.MergeFrom(from.oeirn_cov_);
  linear_vel_.MergeFrom(from.linear_vel_);
  linear_vel_cov_.MergeFrom(from.linear_vel_cov_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_seq()) {
      set_seq(from.seq());
    }
    if (from.has_parent_frame_id()) {
      set_parent_frame_id(from.parent_frame_id());
    }
    if (from.has_frame_id()) {
      set_frame_id(from.frame_id());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_sat_cnt()) {
      set_sat_cnt(from.sat_cnt());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Gnss::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Gnss::CopyFrom(const Gnss& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Gnss::IsInitialized() const {

  return true;
}

void Gnss::Swap(Gnss* other) {
  if (other != this) {
    std::swap(timestamp_, other->timestamp_);
    std::swap(seq_, other->seq_);
    std::swap(parent_frame_id_, other->parent_frame_id_);
    std::swap(frame_id_, other->frame_id_);
    std::swap(status_, other->status_);
    std::swap(type_, other->type_);
    std::swap(sat_cnt_, other->sat_cnt_);
    pos_.Swap(&other->pos_);
    pos_cov_.Swap(&other->pos_cov_);
    orien_.Swap(&other->orien_);
    oeirn_cov_.Swap(&other->oeirn_cov_);
    linear_vel_.Swap(&other->linear_vel_);
    linear_vel_cov_.Swap(&other->linear_vel_cov_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Gnss::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Gnss_descriptor_;
  metadata.reflection = Gnss_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto_msg

// @@protoc_insertion_point(global_scope)
