#@brief: common parameters for Gnss message
common:
  msg_source: 0           #@type: int  @detail: 0--not use Gnss, 1--message come from sensor driver, 2--message come from ROS,3--message come from protobuf(UDP)
  send_msg_ros: false     #@type: bool @detail: if true, the original Gnss message will be sent out through ROS
  send_msg_proto: false   #@type: bool @detail: if true, the original Gnss message will be sent out through Proto

#@brief: config file for sensor driver 
driver:
  include: ../sensor_config/other_sensors/ins/ins_XWG13668.yaml

#@brief: configration for ROS
ros:
  ros_recv_topic: /navsat/fix      
  ros_send_topic: /navsat/fix

#@brief: configration for Proto
proto:
  proto_send_port: 60012
  proto_send_ip: 127.0.0.1
  proto_recv_port: 60012

