#@brief: common parameters for Imu message
common:
  msg_source: 1            #@type: int  @detail: 0--not use Imu, 1--message come from sensor driver, 2--message come from ROS,3--message come from protobuf(UDP)
  send_msg_ros: true      #@type: bool @detail: if true, the original Imu message will be sent out through ROS
  send_msg_proto: false    #@type: bool @detail: if true, the original Imu message will be sent out through Proto

#@brief: config file for sensor driver
driver:
  include: ../sensor_config/other_sensors/imu/imu_DY551.yaml

#@brief: configration for ROS
ros:
  ros_recv_topic: /imu      
  ros_send_topic: /imu
  
#@brief: configration for Proto 
proto:
  proto_send_port: 60011
  proto_send_ip: 127.0.0.1
  proto_recv_port: 60011
  


